<?php
/**
 * @file
 * hr_tools_menu.context.inc
 */

/**
 * Implements hook_context_default_contexts().
 */
function hr_tools_menu_context_default_contexts() {
  $export = array();

  $context = new stdClass();
  $context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
  $context->api_version = 3;
  $context->name = 'block_main_menu';
  $context->description = 'Dummy placement of main menu';
  $context->tag = 'theme';
  $context->conditions = array(
    'sitewide' => array(
      'values' => array(
        1 => 1,
      ),
    ),
  );
  $context->reactions = array(
    'block' => array(
      'blocks' => array(
        'system-main-menu' => array(
          'module' => 'system',
          'delta' => 'main-menu',
          'region' => 'header',
          'weight' => '-10',
        ),
      ),
    ),
  );
  $context->condition_mode = 0;

  // Translatables
  // Included for use with string extractors like potx.
  t('Dummy placement of main menu');
  t('theme');
  $export['block_main_menu'] = $context;

  return $export;
}
